#!/usr/bin/env python3
import random
import time

MARKOV = {
    "miser": (("miser", "laetus", "ebrius"), (3, 5, 2)),
    "laetus": (("miser", "laetus", "ebrius"), (5, 3, 2)),
    "ebrius": (("miser", "laetus"), (5, 5)),
}
status = "miser"
while True:
    print("Sum", status)
    populus, pondera = MARKOV[status]
    status = random.choices(populus, pondera)[0]
    time.sleep(1)
